version: '3.8'
services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "80:80"

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    container_name: git-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
