version: '3.7'
services:
  jenkins:
    user: root
    container_name: jenkins-blueocean
    image: jenkins-blueocean:2.414.3-1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # DooD
    networks:
      - net

networks:
  net:

volumes:
  jenkins-data:
